code/momepy.ipynb

I think that what we currently have in momepy will be of limited use but maybe there's something useful in there.
It currently requires https://github.com/pysal/momepy/pull/546 to get a graph expected by `consolidate_intersections`. That function needs a bit of work before a release.

add momepy workflow

---

README.md
simp-env.yml

(... and added a yml file with the environment i'm using)
thoughts re osmnx simplification see at the bottom of `osmnx.ipynb`

updates to the osmnx notebook

---

README.md

Update README.md - add Wuhan to README

---

README.md

Another `README.md` update.
* new notebook listings
* etc.

updating `README`

---

code/momepy.ipynb

Minor PR to make use of `utils.py` within `momepy.ipynb`

DRY `momepy.ipynb`

---

.github/workflows/testing.yml
.pre-commit-config.yaml
ci/py311_simplification-dev.yaml
ci/py311_simplification-latest.yaml
ci/py311_simplification-oldest.yaml
core/__init__.py
core/tests/test_utils.py
core/utils.py
environment.yml
pyproject.toml
ruff.toml

initial attempt for builing infrastructure - #54
* first small set of tests passing.
* As noted in `.github/workflows/testing.yml`, pathing and data are bit of a pain due to the "convenience" functions I wrote 🙄 . Not sure how we want to proceed with that.
* We can fill in fields in `pyproject.toml` for author, etc later
xref #38

initial attempt for builing infrastructure - #54

---

README.md

CI & coverage badges on README 

---

README.md

update `README.md` for adjusted structure.

---

README.md

Update README.md -- remove `codecov` badge

Update README.md -- remove `codecov` badge

---

core/geometry.py
core/tests/test_geometry.py

This PR:
* resolves #73 
* resolves #74

test & fix for `geomtry.is_within()`

---

ci/py311_simplification-latest.yaml
ci/py311_simplification-oldest.yaml
environment.yml
pyproject.toml

This PR is an initial runs at several minimum pins based upstream in `momepy` & `esda` - also `tobler`
xref #97

initial run with more min pins

---

ci/py311_simplification-oldest.yaml
environment.yml
pyproject.toml

This PR
* resolves #111 
* failures being addressed in #80

pin `tobler>=0.11.3`

---

README.md

Update README.md -- add `core/algorithm/simplify.py`

Update README.md -- add `core/algorithm/simplify`

---

core/algorithms/simplify.py

fix invalid polygon issue

---

core/algorithms/simplify.py
core/geometry.py

This should replace #136 
By decoupling segment length and buffer distance, we can use only a small epsilon in the buffer in some cases which does what we need it to do while not breaking other stuff.

decouple segmentation distance from buffer distance

---

core/algorithms/simplify.py

use larger epsilon

---

core/algorithms/simplify.py

When no dangle is possible (a "loop" is a LineString with two coordinates), this errored.

fix issue with no dangle being possible

---

core/algorithms/simplify.py

Fixes both issue in Liege and the one in Auckland.

fix overlapping line creation

---

.github/workflows/testing.yml
.pre-commit-config.yaml
core/tests/test_protocol.py
core/tests/test_viz_h3_hex.py

This PR:
* resolves #145
* xref #131

resolve #145 -- xfail several tests depending on updated data

---

core/algorithms/simplify.py

I didn't cover the case where there are two primes but both on the same C, which was creating a duplicated line in the end. Fixed

fix CCSS special case issue

---

core/algorithms/simplify.py

Fixes stuff like 
this was more painful than expected

simplify pairs under non-planar line

---

core/algorithms/simplify.py

Reverts uscuni/simplification#150

Revert "simplify pairs under non-planar line"

---

README.md

Update README.md - Resolves #154

Update README.md  - #154 

---

core/algorithms/simplify.py
notebooks/simplification_api_bug.ipynb

Commit 5179799ad44d8ea2e7b81b1c039c9333e8250adc in here fixes #160.
though I am not sure if entirely as it takes a long time to run. but it goes past the original error now :).

Fix the sliver artifact issue causing overlapping lines

---

ci/py311_simplification-latest.yaml
environment.yml
pyproject.toml

* add `sgeop` as a dep
* xref #177

add `sgeop` as a dep

---

.github/workflows/testing.yml

* use token for codecov in testing
* Update testing.yml
* https://github.com/uscuni/sgeop/pull/42#discussion_r1803134567

 use token for codecov in testing

---

README.md
notebooks/preprocessing/clip_networks.ipynb
notebooks/preprocessing/remove_degree_2_nodes.ipynb

updated readme to fit notebook reorganization from #187

Notebooks readme

---

ci/py311_simplification-latest.yaml
environment.yml
pyproject.toml

bump pinned min momepy

---

README.md

add funding note
